---
- hosts: tincdemo
  tasks: 
    - name: update and upgrade
      apt:
          update_cache: yes
          upgrade: yes

    - name: Install tinc
      apt:
          name: tinc
          state: present

    - name: Install mtr
      apt:
          name: mtr
          state: present

    - name: Install inetutils-traceroute
      apt:
          name: inetutils-traceroute
          state: present

    - name: Make directory for VPN hosts
      file:
          name: /etc/tinc/sdinet/hosts
          state: directory

    - name: Make VPN host file
      file:
          name: "/etc/tinc/sdinet/hosts/{{ inventory_hostname }}"
          state: touch

    - name: Template tinc.conf
      template:
          src: tinc.conf.j2
          dest: /etc/tinc/sdinet/tinc.conf

    - name: Nuke old tinc keys
      file:
          name: /etc/tinc/sdinet/rsa_key.priv
          state: absent

    - name: Generate tinc keys
      command:
          cmd: tincd -n sdinet -K 4096

    - name: Add address to hosts file
      lineinfile:
          insertbefore: BOF
          line: "Address = {{ ansible_host }}"
          path: "/etc/tinc/sdinet/hosts/{{ inventory_hostname }}"

    - name: Add IPv4 subnet to host file for host
      lineinfile:
          insertbefore: BOF
          line: "Subnet = {{ cidr }}"
          path: "/etc/tinc/sdinet/hosts/{{ inventory_hostname }}"
   
    - name: Grab keys from hosts
      fetch:
          src: "/etc/tinc/sdinet/hosts/{{ inventory_hostname }}"
          dest: "files/hostkeys/{{ inventory_hostname }}"
          flat: yes

    - name: Push keys to hosts 
      copy:
          src: "files/hostkeys/{{ item }}"
          dest: "/etc/tinc/sdinet/hosts/{{ item }}"
      loop: "{{ ansible_play_batch }}"

    - name: Push topology to hosts
      vars:
          topology_file: "files/topology/{{ inventory_hostname}}"
      blockinfile:
          marker_begin: "BEGIN topology"
          marker_end: "END topology"
          insertafter: "^# CONNECT"
          block: "{{ lookup( 'file', topology_file ) }}"
          dest: /etc/tinc/sdinet/tinc.conf
    
    - name: Template tinc-up
      template:
          src: tinc-up.j2
          dest: /etc/tinc/sdinet/tinc-up
          mode: '0755'

    - name: Template tinc-up
      template:
          src: tinc-down.j2
          dest: /etc/tinc/sdinet/tinc-down
          mode: '0755'

    - name: Add IPv6 subnet to host file for host
      lineinfile:
          insertbefore: BOF
          line: "Subnet = {{ ipv6subnet }}"
          path: "/etc/tinc/sdinet/hosts/{{ inventory_hostname }}"
      when: ipv6subnet is defined

    - name: Add hosts to /etc/hosts
      blockinfile: 
          block: "{{ lookup('file', 'files/etc-hosts') }}"
          dest: /etc/hosts

    - name: Add sdinet to nets.boot
      copy:
          src: nets.boot
          dest: /etc/tinc/nets.boot

    - name: Enable tinc to start at boot
      systemd:
          name: tinc
          enabled: yes
          state: started

    - name: Enable tinc to start at boot
      systemd:
          name: tinc@sdinet
          enabled: yes
          state: started
